---
sudo: required
env:
  - distro: ubuntu1404
    init: /sbin/init
    ANSIBLE_ROLES_PATH: ~/roles

services:
  - docker

install:
  - pip install ansible==2.3.0
  - pip install ansible-lint==3.4.10
  - mkdir "${ANSIBLE_ROLES_PATH}"
  - printf "[defaults]\nhostfile=hosts\nansible_roles=${ANSIBLE_ROLES_PATH}" > ~/.ansible.cfg

script:
  - ./build

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
