---
sudo: required
env:
  - distro: ubuntu1404
    init: /sbin/init

services:
  - docker

install:
  - pip install ansible==2.1.1.0

  # Check ansible version
  - ansible --version

script:
  - ./build

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
