---
- name: create prosperbot-frontend group
  group:
    name: "{{ prosperbot_frontend_group }}"
    state: "present"

- name: create prosperbot-frontend user
  user:
    name: "{{ prosperbot_frontend_user }}"
    group: "{{ prosperbot_frontend_group }}"
    system: "yes"

- name: create gopath directory
  file:
    path: "{{ prosperbot_frontend_gopath }}"
    state: directory
    owner: "{{ prosperbot_frontend_user }}"
    group: "{{ prosperbot_frontend_group }}"

- name: install git
  apt:
    name: git
    state: installed

- name: get prosperbot-frontend app source
  command: go get -u github.com/mtlynch/prosperbot-frontend
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ prosperbot_frontend_goroot }}/bin"
    GOPATH: "{{ prosperbot_frontend_gopath }}"
    GOROOT: "{{ prosperbot_frontend_goroot }}"
  tags:
    # ANSIBLE0012 Commands should not change things if nothing needs doing
    - skip_ansible_lint
  notify:
    - restart prosperbot-frontend

- name: get prosperbot-frontend static source
  git:
    repo: https://github.com/mtlynch/prosperbot-frontend-static.git
    dest: "{{ prosperbot_frontend_static_root }}"
  tags:
    # ANSIBLE0004 Git checkouts must contain explicit version
    - skip_ansible_lint

- name: fix bot-frontend permissions
  file:
    path: "{{ prosperbot_frontend_static_root }}"
    state: directory
    owner: "{{ prosperbot_frontend_user }}"
    group: "{{ prosperbot_frontend_group }}"
    recurse: yes

- name: copy upstart script
  template:
    src: prosperbot-frontend.conf.j2
    dest: /etc/init/prosperbot-frontend.conf
    mode: 0644
  notify:
    - restart prosperbot-frontend

